env_name: 'BaseEnv'
mode: 'online'
load_nn_agent: 'Model_5600.pt'
group: '30_07_continue'
render: False
record: False

#n_episodes: 100
n_steps: 20000
n_epochs: 100
horizon: 300
n_steps_per_fit: 1
num_adv_sample: 50
initial_replay_size: 20000
max_replay_size: 1000000
warmup_transitions: 20000
batch_size: 256
tau: 0.003
dropout_ratio: 0.01
layer_norm: False
#n_eval_episodes: 10
n_eval_steps: 3000
full_save: False

#lr_alpha: 0.00001
#actor_lr: 0.0003
lr_alpha: 0.00001
actor_lr: 0.0003
critic_lr: 0.0003
termination_lr: 0.000003
target_entropy: -2

task_curriculum: False
curriculum_steps: 10

check_point__: "./logs/static_hit_2024-07-29_16-04-22/parallel_seed___1/0/BaseEnv_2024-07-29-16-19-05"

sweep_params:
  parallel_seed__: [0, 1, 2]


experiments:
  exp_name: 'static_hit'
  exp_file: 'train_t_sac_static_hit'
  n_seeds: 1
  n_cores: 4
  n_exps_in_parallel: 1
  memory_single_job: 3000
  days: 0
  hours: 23
  minutes: 59
  seconds: 0
  partition: 'stud'
  gres: 'gpu:1'   # if use_cuda 'gpu:1'
  conda_env: 'neural_planner'
  use_timestamp: True
  compact_dirs: False
  use_cuda: True


