env_name: 'HitBackEnv'
mode: 'online'
group: '05_09_new_r/horizon_curriculum/adv_0.5/two_opponent/300/against_08_29_opponent_and_baseline/0.99'
render: False
record: False

adv_bonus: 0.5
#n_episodes: 100
n_steps: 20000
n_epochs: 100
horizon: 300
n_steps_per_fit: 1
num_adv_sample: 50
initial_replay_size: 20000
max_replay_size: 1000000
warmup_transitions: 20000
termination_warmup: 60000
batch_size: 256
tau: 0.003
dropout_ratio: 0.01
layer_norm: False
#n_eval_episodes: 10
n_eval_steps: 5000
full_save: False

#lr_alpha: 0.00001
#actor_lr: 0.0003
gamma: 0.99
lr_alpha: 0.00001
actor_lr: 0.0003
critic_lr: 0.0003
termination_lr: 0.00001
target_entropy: -2

task_curriculum: False
curriculum_steps: 6

#check_point__: "t_sac_2024-08-27_10-24-18/parallel_seed___2/0/HitBackEnv_2024-08-27-10-59-22"

sweep_params:
  parallel_seed__: [0]


experiments:
  exp_name: 't_sac'
  exp_file: 'train_t_sac_exp'
  n_seeds: 1
  n_cores: 4
  n_exps_in_parallel: 1
  memory_single_job: 3000
  days: 0
  hours: 23
  minutes: 59
  seconds: 0
  partition: 'stud3080'
  gres: 'gpu:1'   # if use_cuda 'gpu:1'
  conda_env: 'neural_planner'
  use_timestamp: True
  compact_dirs: False
  use_cuda: True



